# Exercises

In [18]:
import numpy as np

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [19]:

# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]
new_height = np.array(height)
new_weight = np.array(weight)

BMI = new_weight / (new_height**2) * 730
print(BMI)



[16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [31]:
def make_matrix(a, b, c):
    arr = np.arange(a, b).reshape(c)
    return arr

print(make_matrix(0,9, (3, 3)))

# """
# Example Result for make_matrix(0,15,(3,3)):
# array([[14.21633515,  7.98846653,  9.64140715],
#        [ 6.30982234,  9.96414331,  8.43153688],
#        [14.73102068, 11.76072894, 14.23356121]])
# """
# def make_matrix(low,high,shape,data_type = float): -- Example
#     pass

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [34]:
arr_range = np.arange(0, 4).reshape(2, 2)
print(arr_range)


[[0 1]
 [2 3]]


### #3 - Open and load the data for the Chicago White Sox hitting data for this past season.Create a function that will compare the infield players output vs the outfield players output vs *hybrid. (Infield - {C, 1B, 2B, SS, 3B, MI}, Outfield - {LF, CF, RF, OF}, *Hybrid - {DH, UT}) for a specific stat. i.e. BA or HR or OPS

*Hybrid is optional


In [36]:
import csv
import numpy as np

#Test to make sure you have the correct data
def open_csv(filename, d=','):
    # define an empty list to store our data
    data = []
    
    # open up the file 
    with open(filename, encoding='utf-8') as white_sox:
        # and create csv reader object
        reader = csv.reader(white_sox, delimiter=d)
        
        # Iterate over each row in the csv and append it to the data list
        for row in reader:
            data.append(row)
    return data

white_sox = open_csv('whitesox_2021_hitting.csv')

# Open the data into an array
def load_data(filename, d=','):
    data = np.genfromtxt(filename, dtype=DATATYPES, delimiter=d, names=True, invalid_raise=False)
    return data

In [37]:
white_sox

[['Rk',
  'Pos',
  'Name',
  'Age',
  'G',
  'PA',
  'AB',
  'R',
  'H',
  '2B',
  '3B',
  'HR',
  'RBI',
  'SB',
  'CS',
  'BB',
  'SO',
  'BA',
  'OBP',
  'SLG',
  'OPS',
  'OPS+',
  'TB',
  'GDP',
  'HBP',
  'SH',
  'SF',
  'IBB'],
 ['1',
  'C',
  'Yasmani Grandal',
  '32',
  '93',
  '375',
  '279',
  '60',
  '67',
  '9',
  '0',
  '23',
  '62',
  '0',
  '0',
  '87',
  '82',
  '.240',
  '.420',
  '.520',
  '.939',
  '157',
  '145',
  '15',
  '3',
  '1',
  '5',
  '0'],
 ['2',
  '1B',
  'José Abreu',
  '34',
  '152',
  '659',
  '566',
  '86',
  '148',
  '30',
  '2',
  '30',
  '117',
  '1',
  '0',
  '61',
  '143',
  '.261',
  '.351',
  '.481',
  '.831',
  '125',
  '272',
  '28',
  '22',
  '0',
  '10',
  '3'],
 ['3',
  '2B',
  'Cesar Hernandez',
  '31',
  '53',
  '217',
  '194',
  '24',
  '45',
  '4',
  '0',
  '3',
  '15',
  '1',
  '1',
  '21',
  '45',
  '.232',
  '.309',
  '.299',
  '.608',
  '69',
  '58',
  '5',
  '1',
  '0',
  '1',
  '2'],
 ['4',
  'SS',
  'Tim Anderson',
  '28',
  '1

In [45]:


FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray
# Open the data into an array
def load_data(filename, d=','):
    data = np.genfromtxt(filename, dtype=DATATYPES, delimiter=d, names=True, invalid_raise=False)
    return data

whitesox_2021 = load_data('whitesox_2021_hitting.csv')

whitesox_2021

names = whitesox_2021['Name']
print(names)
infield = ['C, 1B, 2B, SS, 3B, MI'] 
Outfield = ['LF, CF, RF, OF']
hybrid = ['DH, UT']

[b'Yasmani Grandal' b'Jos\xc3\xa9 Abreu' b'Cesar Hernandez'
 b'Tim Anderson' b'Yoan Moncada' b'Andrew Vaughn' b'Luis Robert'
 b'Adam Eaton' b'Yermin Mercedes' b'Leury Garcia' b'Brian Goodwin'
 b'Eloy Jimenez' b'Zack Collins' b'Nick Madrigal' b'Danny Mendick'
 b'Gavin Sheets' b'Adam Engel' b'Billy Hamilton' b'Jake Lamb'
 b'Seby Zavala' b'Jake Burger' b'Romy Gonzalez' b'Nick Williams'
 b'Luis Gonzalez']
